"use client";

import { useState } from "react";
import { Bell, Check, Download, Gift, Megaphone, Plus, Search, ShieldCheck, Star, UserPlus, Users } from "lucide-react";
import { usePrototype } from "@/components/prototype/prototype-provider";
import { BarChart, Modal, SectionHeader, StatusBadge } from "@/components/ui/prototype-ui";
import type { Customer } from "@/lib/types";

type ToastFn = (message: string) => void;

export function CustomersModule({ toast }: { toast: ToastFn }) {
  const { customers } = usePrototype();
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Customer | null>(null);
  const [tab, setTab] = useState("Customers");
  const shown = customers.filter((customer) => customer.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="module-page">
    <SectionHeader title="Customers & loyalty" description="Understand every guest and bring them back" actions={<button className="btn btn-primary" onClick={() => toast("New customer form opened in demo mode")}><UserPlus size={15} />Add customer</button>} />
    <div className="metric-grid mini"><article className="metric-card plain"><p>Total customers</p><strong>1,248</strong><small className="success-text">+32 this month</small></article><article className="metric-card plain"><p>Returning rate</p><strong>68.4%</strong><small>Industry avg. 54%</small></article><article className="metric-card plain"><p>Loyalty members</p><strong>842</strong><small>67% of customers</small></article><article className="metric-card plain"><p>Customer value</p><strong>LKR 18,420</strong><small>Average lifetime spend</small></article></div>
    <div className="module-tabs">{["Customers", "Loyalty", "Campaigns", "Feedback"].map((value) => <button className={tab === value ? "active" : ""} key={value} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === "Customers" && <><label className="field-search standalone"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customers…" /></label><div className="customer-grid">{shown.map((customer) => <button className="panel customer-card" key={customer.id} onClick={() => setSelected(customer)}><div className="customer-top"><span>{customer.name.split(" ").map((n) => n[0]).join("")}</span><StatusBadge tone={customer.segment}>{customer.segment}</StatusBadge></div><h3>{customer.name}</h3><p>{customer.favorite} · {customer.visits} visits</p><div><span><small>Total spent</small><strong>LKR {customer.spent.toLocaleString()}</strong></span><span><small>Points</small><strong>{customer.points}</strong></span></div></button>)}</div></>}
    {tab === "Loyalty" && <div className="loyalty-layout"><article className="panel loyalty-hero"><span><Gift /></span><div><p>Bloom Rewards</p><h2>Turn every coffee into a reason to return.</h2><small>LKR 100 = 1 point · 500 points = LKR 500 reward</small><button className="btn btn-primary" onClick={() => toast("Loyalty settings saved")}>Configure rewards</button></div></article><div className="loyalty-stats"><article className="panel"><strong>18,420</strong><span>Points earned this month</span></article><article className="panel"><strong>42</strong><span>Rewards redeemed</span></article><article className="panel"><strong>LKR 24,600</strong><span>Revenue from rewards</span></article></div></div>}
    {tab === "Campaigns" && <div className="campaign-grid"><CampaignCard icon={<Megaphone />} title="Win back regulars" audience="86 customers" offer="15% off next visit" tone="green" toast={toast} /><CampaignCard icon={<Gift />} title="September birthdays" audience="24 customers" offer="Free birthday drink" tone="purple" toast={toast} /><CampaignCard icon={<Star />} title="VIP early access" audience="42 customers" offer="New menu tasting" tone="amber" toast={toast} /></div>}
    {tab === "Feedback" && <div className="feedback-grid"><article className="panel rating-panel"><strong>4.8</strong><div>★★★★★</div><p>From 328 verified orders</p></article><article className="panel feedback-list"><h3>Recent feedback</h3>{["The oat milk latte was perfect!", "Fast pickup and lovely staff.", "Croissant was warm and flaky."].map((quote, index) => <div key={quote}><span>{["NJ", "KP", "AR"][index]}</span><p><b>★★★★★</b>{quote}</p><small>{index + 1} day ago</small></div>)}</article></div>}
    <Modal open={!!selected} onClose={() => setSelected(null)} title="Customer profile"><div className="profile-modal"><div className="profile-identity"><span>{selected?.name.split(" ").map((n) => n[0]).join("")}</span><div><h2>{selected?.name}</h2><p>{selected?.email}<br />{selected?.phone}</p></div></div><div className="profile-stats"><div><small>Total spent</small><strong>LKR {selected?.spent.toLocaleString()}</strong></div><div><small>Visits</small><strong>{selected?.visits}</strong></div><div><small>Points</small><strong>{selected?.points}</strong></div></div><div className="profile-favorite"><span>☕</span><div><small>Favourite order</small><strong>{selected?.favorite}</strong><p>Usually visits 3–4 times per month</p></div></div><button className="btn btn-primary btn-full" onClick={() => { setSelected(null); toast("Offer sent by WhatsApp"); }}>Send a personalised offer</button></div></Modal>
  </div>;
}

function CampaignCard({ icon, title, audience, offer, tone, toast }: { icon: React.ReactNode; title: string; audience: string; offer: string; tone: string; toast: ToastFn }) {
  return <article className={`panel campaign-card ${tone}`}><span>{icon}</span><StatusBadge tone="draft">Draft</StatusBadge><h3>{title}</h3><p>{audience}</p><div><small>Automated offer</small><strong>{offer}</strong></div><button className="btn btn-secondary" onClick={() => toast(`${title} campaign launched`)}>Review and launch</button></article>;
}

export function TeamModule({ toast }: { toast: ToastFn }) {
  const { employees } = usePrototype();
  const [tab, setTab] = useState("Schedule");
  const days = ["Mon 14", "Tue 15", "Wed 16", "Thu 17", "Fri 18", "Sat 19", "Sun 20"];
  return <div className="module-page">
    <SectionHeader title="Team" description="Schedule, attendance and labour in one place" actions={<button className="btn btn-primary" onClick={() => toast("Invite link copied")}><Plus size={15} />Add team member</button>} />
    <div className="metric-grid mini"><article className="metric-card plain"><p>Working now</p><strong>8</strong><small>of 12 scheduled today</small></article><article className="metric-card plain"><p>Labour today</p><strong>LKR 21,400</strong><small>11.6% of projected sales</small></article><article className="metric-card plain"><p>On time</p><strong>94%</strong><small className="success-text">+3% this month</small></article><article className="metric-card plain"><p>Open shifts</p><strong>2</strong><small className="warning-text">Weekend coverage</small></article></div>
    <div className="module-tabs">{["Schedule", "Employees", "Attendance", "Roles"].map((value) => <button className={tab === value ? "active" : ""} key={value} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === "Schedule" && <div className="schedule panel"><div className="schedule-head"><strong>Week of 14 September</strong><div><button>‹</button><button>Today</button><button>›</button></div></div><div className="schedule-grid"><div className="schedule-names"><span>Team member</span>{employees.map((employee) => <div key={employee.id}><i>{employee.avatar}</i><div><strong>{employee.name}</strong><small>{employee.role}</small></div></div>)}</div>{days.map((day, dayIndex) => <div className={`schedule-day ${dayIndex === 3 ? "today" : ""}`} key={day}><span>{day}</span>{employees.map((employee, empIndex) => <button className={`${(dayIndex + empIndex) % 5 === 0 ? "off" : "shift"}`} key={employee.id} onClick={() => toast(`${employee.name}'s shift opened`)}>{(dayIndex + empIndex) % 5 === 0 ? "Off" : empIndex > 2 ? "12–20" : "06–14"}</button>)}</div>)}</div></div>}
    {tab === "Employees" && <div className="employee-grid">{employees.map((employee) => <article className="panel employee-card" key={employee.id}><div><span>{employee.avatar}</span><StatusBadge tone={employee.status}>{employee.status}</StatusBadge></div><h3>{employee.name}</h3><p>{employee.role}</p><dl><div><dt>Today</dt><dd>{employee.shift}</dd></div><div><dt>This week</dt><dd>{employee.hours} h</dd></div></dl><button onClick={() => toast(`${employee.name}'s profile opened`)}>View profile →</button></article>)}</div>}
    {tab === "Attendance" && <div className="data-table attendance-table panel"><div className="table-head"><span>Employee</span><span>Scheduled</span><span>Clock in</span><span>Clock out</span><span>Hours</span><span>Status</span></div>{employees.map((employee, index) => <div className="table-row" key={employee.id}><strong>{employee.name}</strong><span>{employee.shift}</span><span>{index === 2 ? "07:18" : index > 2 ? "—" : "06:02"}</span><span>{index > 1 ? "—" : "14:01"}</span><b>{index > 1 ? "—" : "7h 59m"}</b><StatusBadge tone={employee.status}>{employee.status}</StatusBadge></div>)}</div>}
    {tab === "Roles" && <div className="roles-grid">{["Owner", "Manager", "Cashier", "Barista", "Kitchen"].map((role, index) => <article className="panel role-card" key={role}><ShieldCheck /><h3>{role}</h3><p>{[1, 2, 3, 5, 2][index]} team members</p><ul><li>Access {index < 2 ? "all reports" : "assigned operations"}</li><li>{index < 2 ? "Manage team and stock" : "No financial reports"}</li><li>{index === 0 ? "Full settings access" : "Limited settings"}</li></ul><button onClick={() => toast(`${role} permissions opened`)}>Edit permissions</button></article>)}</div>}
  </div>;
}

export function ReportsModule({ toast }: { toast: ToastFn }) {
  const [range, setRange] = useState("Last 7 days");
  return <div className="module-page">
    <SectionHeader title="Reports & analytics" description="Know what changed, why it changed and what to do next" actions={<><select className="select-control" value={range} onChange={(e) => setRange(e.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>This year</option></select><button className="btn btn-secondary" onClick={() => toast("CSV report exported")}><Download size={15} />Export</button></>} />
    <div className="metric-grid mini"><article className="metric-card plain"><p>Revenue</p><strong>LKR 1.18M</strong><small className="success-text">+12.8% vs prior period</small></article><article className="metric-card plain"><p>Gross profit</p><strong>LKR 766K</strong><small>65.1% margin</small></article><article className="metric-card plain"><p>COGS</p><strong>LKR 411K</strong><small className="warning-text">+2.2% vs target</small></article><article className="metric-card plain"><p>Estimated net</p><strong>LKR 462K</strong><small className="success-text">39.2% net margin</small></article></div>
    <div className="reports-grid"><article className="panel report-main"><div className="panel-head"><div><p>Revenue by day</p><h2>LKR 1,177,420</h2></div><StatusBadge tone="healthy">↗ 12.8%</StatusBadge></div><BarChart values={[118, 142, 131, 166, 149, 192, 184]} labels={["Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"]} /></article><article className="panel channel-panel"><div className="panel-head"><div><p>Order channels</p><h3>1,986 orders</h3></div></div><div className="donut"><div><strong>1,986</strong><span>orders</span></div></div><ul><li><i className="dine" />Dine in <strong>62%</strong></li><li><i className="pickup" />Pickup <strong>24%</strong></li><li><i className="delivery" />Delivery <strong>14%</strong></li></ul></article></div>
    <div className="reports-grid lower"><article className="panel product-performance"><div className="panel-head"><div><p>Product performance</p><h3>Menu engineering</h3></div><button>View full report →</button></div>{[["Iced Latte", "Star", 420, "68%", "LKR 239K"], ["Cappuccino", "Star", 280, "66%", "LKR 148K"], ["Matcha Latte", "Puzzle", 150, "59%", "LKR 84K"], ["Mango Smoothie", "Opportunity", 80, "54%", "LKR 42K"]].map((row) => <div key={row[0]}><strong>{row[0]}</strong><StatusBadge tone={row[1] as string}>{row[1]}</StatusBadge><span>{row[2]} sold</span><span>{row[3]} margin</span><b>{row[4]}</b></div>)}</article><article className="panel insight-card"><span><Bell /></span><p>Key insight</p><h2>Your strongest hour is 9–10 AM.</h2><small>Revenue is 38% higher than the daily hourly average. Consider adding one barista to reduce average fulfillment time by 2.4 minutes.</small><button onClick={() => toast("Recommendation added to tasks")}>Add to action plan</button></article></div>
  </div>;
}

export function SettingsModule({ toast }: { toast: ToastFn }) {
  const [saved, setSaved] = useState(false);
  const [tab, setTab] = useState("Café");
  function save() { setSaved(true); toast("Settings saved"); window.setTimeout(() => setSaved(false), 1800); }
  return <div className="module-page">
    <SectionHeader title="Settings" description="Manage your café, team access and integrations" actions={<button className="btn btn-primary" onClick={save}>{saved ? <Check size={15} /> : null}{saved ? "Saved" : "Save changes"}</button>} />
    <div className="settings-layout"><aside className="settings-nav">{["Café", "Branches", "Users & roles", "Payments", "Integrations", "Notifications", "Audit log"].map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</aside><section className="panel settings-panel">
      {tab === "Café" && <><div className="settings-title"><h2>Café profile</h2><p>This information appears on receipts and customer ordering pages.</p></div><div className="form-grid"><label>Café name<input defaultValue="Bloom Coffee" /></label><label>Business registration<input defaultValue="PV 00298421" /></label><label>Support email<input defaultValue="hello@bloomcoffee.lk" /></label><label>Phone<input defaultValue="+94 11 234 8800" /></label><label>Currency<select defaultValue="LKR"><option>LKR</option><option>USD</option></select></label><label>Timezone<select defaultValue="Asia/Colombo"><option>Asia/Colombo</option></select></label><label className="span-2">Address<textarea defaultValue="42 Flower Road, Colombo 07, Sri Lanka" /></label></div></>}
      {tab === "Integrations" && <><div className="settings-title"><h2>Integrations</h2><p>Connect the tools your café already uses.</p></div><div className="integration-list">{[["WhatsApp Business", "Customer receipts and campaigns", "Connected"], ["Stripe", "Online card payments", "Connected"], ["PickMe Food", "Delivery order sync", "Connect"], ["Xero", "Accounting export", "Connect"]].map((item) => <div key={item[0]}><span>{item[0][0]}</span><div><strong>{item[0]}</strong><small>{item[1]}</small></div><button className={item[2] === "Connected" ? "connected" : ""} onClick={() => toast(`${item[0]} connection updated`)}>{item[2]}</button></div>)}</div></>}
      {tab === "Notifications" && <><div className="settings-title"><h2>Notifications</h2><p>Choose what should get your attention.</p></div><div className="notification-settings">{["Low-stock and expiry alerts", "Large refunds and voids", "Team late arrivals", "Daily performance summary", "AI recommendations"].map((item, index) => <label key={item}><div><strong>{item}</strong><small>{index === 4 ? "Weekly, when there is a high-confidence opportunity" : "Notify owner and branch manager"}</small></div><input type="checkbox" defaultChecked={index !== 2} /></label>)}</div></>}
      {tab !== "Café" && tab !== "Integrations" && tab !== "Notifications" && <div className="placeholder-panel embedded"><Users size={28} /><h2>{tab}</h2><p>Review and configure demo {tab.toLowerCase()} records.</p><button className="btn btn-secondary" onClick={() => toast(`${tab} settings opened`)}>Manage {tab.toLowerCase()}</button></div>}
    </section></div>
  </div>;
}
